version: '4.32.0'
services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: api_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: .
    environment:
      MYSQL_PASS: ${MYSQL_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - db
  ui:
    build:
      context: ./ui
    command: npm start
    depends_on:
      - api
    ports:
      - "3000:3000"